# OpenSearch with the Prometheus exporter plugin (metrics at /_prometheus/metrics).
# The plugin version must match the OpenSearch version exactly (3.8.0 -> 3.8.0.0).
ARG OPENSEARCH_VERSION=3.8.0

FROM opensearchproject/opensearch:${OPENSEARCH_VERSION}
ARG OPENSEARCH_VERSION
RUN /usr/share/opensearch/bin/opensearch-plugin install --batch \
    "https://github.com/opensearch-project/opensearch-prometheus-exporter/releases/download/${OPENSEARCH_VERSION}.0/prometheus-exporter-${OPENSEARCH_VERSION}.0.zip"
